### PR TITLE
Modified updater for pixels

### PR DESCRIPTION
**Pull request by chaodaiG**
This is pretty much copy/paste from cmd/updater

### CODE REVIEW

**Comment by chaodaiG** [comment]
/cc @fejta 
I haven't yet figured out how to let it update only my board yet

**Comment by fejta** [comment]
`go run ./cmd/updater --test-group=chaodaiG`

**Comment by chaodaiG** [comment]
https://testgrid.k8s.io/r/k8s-testgrid-hackathon/everyone#chaodaiG

**Comment by fejta** [comment]
Cool! I'd recommend using size compact: https://testgrid.k8s.io/r/k8s-testgrid-hackathon/everyone#chaodaiG&width=20

**Comment by chaodaiG** [comment]
/hold
The output doesn't match input, let me dig

**Comment by fejta** [comment]
Also sort-by name: https://testgrid.k8s.io/r/k8s-testgrid-hackathon/everyone#chaodaiG&width=20&sort-by-name=

**Comment by chaodaiG** [comment]
It's correct after sorting, so
/unhold

**Comment by fejta** [comment]
lgtm

**Comment by chaodaiG** [comment]
fyi @e-blackwelder @cjwagner @mpherman2 : this PR adds lib method `Update` from `hackathon/pkg/hackupdater/updater.go`

**Pull request merged**
