### PR TITLE
Add a new function converting string to ASCII

### PR DESCRIPTION
**Pull request by chaodaiG**
/cc @cjwagner @mpherman2 @e-blackwelder

### CODE REVIEW

**Comment by chaodaiG** [comment]
See ABC at https://testgrid.k8s.io/r/k8s-testgrid-hackathon/everyone#chaodaiG&width=20&sort-by-name=

**Comment by e-blackwelder** [comment]
Nice! Could we get spaces/padding around the characters?

**Comment by chaodaiG** [comment]
Added a reference implementation, see 
Screen Shot 2021-06-15 at 8 16 59 AM

**Comment by chaodaiG** [comment]
Game board created

Screen Shot 2021-06-15 at 12 44 28 PM

**Comment by chaodaiG** [comment]
Large letters:
Screen Shot 2021-06-15 at 12 45 29 PM

**Pull request merged**
